# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='honorific',
            new_name='title',
        ),
    ]
