# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_project_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Project_stage'),
            preserve_default=False,
        ),
    ]
