# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_project_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='funder',
        ),
        migrations.AddField(
            model_name='project',
            name='funders',
            field=models.ManyToManyField(to='backend.Funder'),
        ),
    ]
