# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170712_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255, unique=True)),
                ('aims_and_activities', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(blank=True, choices=[('PROP', 'Proposed'), ('CURR', 'Current'), ('COMP', 'Completed')], max_length=4),
        ),
        migrations.DeleteModel(
            name='Project_stage',
        ),
    ]
