# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:28
from __future__ import unicode_literals

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('backend', '0005_auto_20170712_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
