# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:28
from __future__ import unicode_literals

from django.db import migrations

def create_my_user(apps, schema_editor):
    from django.contrib.auth.models import User
    User.objects.create_superuser('tom', 'myuser@mydomain.com', 'foobarbaz')

def forwards_func(apps, schema_editor):
    Activity = apps.get_model("backend", "Activity")
    Skill = apps.get_model("backend", "Skill")
    db_alias = schema_editor.connection.alias
    Activity.objects.using(db_alias).bulk_create([
        Activity(name="Practical", lft=1, rght=6, tree_id=1, level=0),
        Activity(name="Building Work", lft=2, rght=3, tree_id=1, level=1, parent_id=1),
        Activity(name="Gardening", lft=4, rght=5, tree_id=1, level=1, parent_id=1),
        Activity(name="Professional", lft=1, rght=6, tree_id=2, level=0),
        Activity(name="Financial Control", lft=2, rght=3, tree_id=2, level=1, parent_id=4),
        Activity(name="Management", lft=4, rght=5, tree_id=2, level=1, parent_id=4),
    ])
    Skill.objects.using(db_alias).bulk_create([
        Skill(name="Creative", lft=1, rght=8, tree_id=1, level=0),
        Skill(name="Craft", lft=2, rght=3, tree_id=1, level=1, parent_id=1),
        Skill(name="Design", lft=4, rght=5, tree_id=1, level=1, parent_id=1),
        Skill(name="Photography", lft=6, rght=7, tree_id=1, level=1, parent_id=1),
        Skill(name="Practical", lft=1, rght=6, tree_id=2, level=0),
        Skill(name="Building Work", lft=2, rght=3, tree_id=2, level=1, parent_id=5),
        Skill(name="Carpentry", lft=4, rght=5, tree_id=2, level=1, parent_id=5),
    ])

def reverse_func(apps, schema_editor):
    Activity = apps.get_model("backend", "Activity")
    db_alias = schema_editor.connection.alias
    Activity.objects.using(db_alias).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20170923_1553'),
    ]

    # operations = [
    #     migrations.RunPython(create_my_user),
    # ]
    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RunPython(create_my_user),
    ]
