# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 16:45
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    OrganisationType = apps.get_model("backend", "OrganisationType")
    db_alias = schema_editor.connection.alias
    OrganisationType.objects.using(db_alias).bulk_create([
        OrganisationType(name="Registered Charity – Unincorporated Association"),
        OrganisationType(name="Registered Charity – Charitable Incorporated Organisation", acronym="CIO"),
        OrganisationType(name="Community Interest Company", acronym="CIC"),
        OrganisationType(name="Company Limited by Guarantee", acronym="CLG"),
        OrganisationType(name="Industrial & Provident", acronym="I & P"),
        OrganisationType(name="Unincorporated Association - not registered with Charity Commission"),
        OrganisationType(name="Social Enterprise", acronym="SE"),
    ])


def reverse_func(apps, schema_editor):
    OrganisationType = apps.get_model("backend", "OrganisationType")
    db_alias = schema_editor.connection.alias
    OrganisationType.objects.using(db_alias).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20170925_2058'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
